### ISSUE TITLE
Tests test_2B_involution and test_xx failing when I build in MacOS 12.1

### ISSUE THREAD

**Issue by hwatheod** [Martin-Seysen/mmgroup#1]
Quick summary:

These tests failed when I ran with `python -m pytest ./src/mmgroup/ -v -s -m "not slow"`:

```
FAILED src/mmgroup/tests/test_involutions/test_2B_involution.py::test_2B_involution - ValueError: Conjugation of element to central involution failed
FAILED src/mmgroup/tests/test_involutions/test_involution_invariants.py::test_xx - assert 0 == 4
```

Longer details on what I did:

First, I just want to say that I'm so excited to see there's a Python implementation of the monster group. I tried so many times before to learn about the monster from Conway's article and other sources but without software to experiment, it was just very difficult.

I'm building on MacOS 12.1.  I used `python setup.py install -f` but I had to make the following changes:

1. Change all `#include <malloc.h>` to `#include <stdlib.h>` in the .ske files
2. Remove the parameter `-static-libgcc` from everywhere in `config.py` (my compiler said that option is not supported)
3. After building, when I tried to create a monster element with something like `u = MM('d', 0x246)`, I got an error saying `No module named 'mmgroup.mm_reduce'`. I discovered that the boostrap `mm_reduce.py` and the library file `mm_reduce.cpython-38-darwin.so` didn't make it into the egg (but the library did get built). So I copied the library to the right place in my Python virtual environment , and then I created the `mm_reduce.py` myself by copying one of the other bootstrap `.py` files and changing the filename for the library.

After I did all that, the errors went away and I could create 2 monster elements and multiply them. But when I tried to run the tests, I got the 2 failures above.

**Comment by Martin-Seysen** [comment]
>> These tests failed when I ran with python -m pytest ./src/mmgroup/ -v -s -m "not slow":

   It appears to me that you have gone rather deep into the setup process.
   So my following comments might be helpful for you.


>> FAILED src/mmgroup/tests/test_involutions/test_2B_involution.py::test_2B_involution - ValueError: Conjugation of element to central involution failed

   Failure 2 appears at a lower level than Failure 1. So I suggest to deal with Failure 2 first.

>> FAILED src/mmgroup/tests/test_involutions/test_involution_invariants.py::test_xx - assert 0 == 4
   For debbuging I do the following:

   In file src/mmgroup/tests/test_involutions/test_involution_invariants.py,
   for debugging I temporarily change the lines

 ```
   @pytest.mark.involution
   def test_xx(verbose = 0):
       ...
```
   to 

```
   @pytest.mark.mmm
   @pytest.mark.involution
   def test_xx(verbose = 1):
       ...
```
   Then I run 

```
   python -m pytest ./src/mmgroup/ -v -s -m "mmm"
```

   This gives a more verbose and more specific output of the failing test.

   If you can send me the output of that test and also your modified file
   .../test_involution_invariants.py
   then I might be able to fix this problem.

>> Longer details on what I did:
>> First, I just want to say that I'm so excited to see there's a Python implementation of the monster group. I tried so many times before to learn about the monster from Conway's article and other sources but without software to experiment, it was just very difficult.

   I appreciate that you are using my monster group implementation!

>> I'm building on MacOS 12.1. I used python setup.py install -f but I had to make the following changes:

   I have no experience with MacOS. I guess that this is similar to a Linux system.
   Otherwise I doubt that setup.py would work at all. You may call

```
   python setup.py build_ext --help-compiler
```

   to obtain a list of C compilers supported. 
   It is important to know which compiler you actually use.
   At present I support MSVC and gcc only.
 
>>     Change all #include <malloc.h> to #include <stdlib.h> in the .ske files

   There are some preprocessor variables set by the compiler automatically.
   At present I use preprocessor variables like ``_WIN32``, ``__CYGWIN__``, ``__GNUC__`` in 
   the header files to distinguish between operating systems and compilers. If
   there is a reasonable way to identify your compiler with preprocessor
   variables, I might include some '#ifdef' statements in the sources to treat
   your compiler appropriately. But therefore I need more information from you. 

>>     Remove the parameter -static-libgcc from everywhere in config.py (my compiler said that option is not supported)

   So this change appears to work well for you. If you can give me some more
   specific information about this issue then I might include it into the 
   documentation in order to simplify life for other users.  

>>     After building, when I tried to create a monster element with something like u = MM('d', 0x246), I got an error saying No module named 'mmgroup.mm_reduce'. I discovered that the boostrap mm_reduce.py and the library file mm_reduce.cpython-38-darwin.so didn't make it into the egg (but the library did get built). So I copied the library to the right place in my Python virtual environment , and then I created the mm_reduce.py myself by copying one of the other bootstrap .py files and changing the filename for the library.

   'mmgroup.mm_reduce' is a Cython extension. There is a file 

   src/mmgroup/dev/mm_reduce/mm_reduce.pyx

   defining the Cython extension 'mmgroup.mm_reduce',
   but no file 'mm_reduce.py'.
   In my Linux environment the setup process generates a shared librry

   src/mmgroup/mm_reduce.cython-39-x86_64-linux-gnu.so

   that contains the 'mmgroup.mm_reduce' extension. The name of the
   shared library may be different in your system.
   So in Linux a Cython extension is implemented as a shared library.
   Here such a shared library calls functions from other shared libraries.
   In a Linux shell I have to enter something like:
 
```  
   export LD_LIBRARY_PATH=<project directory>/src/mmgroup
```

   This sets the envrionment variable ``LD_LIBRARY_PATH`` appropriately,
   so that the shared libraries used by the Cython extensions can be found.

   I dont't know if there is an equivalent environment variable in MacOS.

**Comment by hwatheod** [comment]
> If you can send me the output of that test and also your modified file
> .../test_involution_invariants.py
> then I might be able to fix this problem.

Here's the output from the failed test
[failed_test_xx.txt](https://github.com/Martin-Seysen/mmgroup/files/8239097/failed_test_xx.txt)

The only changes I made to `test_involution_invariants.py` are the ones you suggested above (adding py.mark.mmm and setting verbose=1 for test_xx).


> I have no experience with MacOS. I guess that this is similar to a Linux system.

Yes, MacOS is similar (enough) to Linux that a lot of the same build setups will work with some small changes.


> 
>         Change all #include <malloc.h> to #include <stdlib.h> in the .ske files
> 
> There are some preprocessor variables set by the compiler automatically.
> At present I use preprocessor variables like _WIN32, __CYGWIN__, __GNUC__ in
> the header files to distinguish between operating systems and compilers. If
> there is a reasonable way to identify your compiler with preprocessor
> variables, I might include some '#ifdef' statements in the sources to treat
> your compiler appropriately. But therefore I need more information from you.

My compiler is Apple's [clang](https://opensource.apple.com/source/clang/clang-23/clang/tools/clang/docs/UsersManual.html). However, I am not sure that is the issue. This [StackOverflow answer](https://stackoverflow.com/questions/12973311/difference-between-stdlib-h-and-malloc-h) says that `malloc.h` is deprecated and should be replaced by `stdlib.h`.


> 
>         Remove the parameter -static-libgcc from everywhere in config.py (my compiler said that option is not supported)
> 
> So this change appears to work well for you. If you can give me some more
> specific information about this issue then I might include it into the
> documentation in order to simplify life for other users.

I'm not sure what else I can add besides that clang doesn't seem to support this option.

> In a Linux shell I have to enter something like:
> 
>    export LD_LIBRARY_PATH=<project directory>/src/mmgroup
> 
> This sets the envrionment variable LD_LIBRARY_PATH appropriately,
> so that the shared libraries used by the Cython extensions can be found.
> 

Yes, I can now see that would have also fixed the problem and is better than my solution which requires modifying the source.

**Comment by hwatheod** [comment]
Here are the logs from the build and the test_xx (with verbose=1 setting) for the latest version (commit d2c77d4).
[build_d2c77d4.txt](https://github.com/Martin-Seysen/mmgroup/files/8279916/build_d2c77d4.txt)
[test_xx_failure_d2c77d4.txt](https://github.com/Martin-Seysen/mmgroup/files/8279917/test_xx_failure_d2c77d4.txt)

Also, I cannot get the LD_LIBRARY_PATH solution to work. I've upgraded to MacOS 12.3 in the last few days and now I found that the build behavior is different again. Under MacOS 12.1, the build process generated files like this

clifford12.py
generators.py
mat24.py
mm.py
mm127.py
mm15.py
mm255.py
mm3.py
mm31.py
mm7.py
mm_reduce.py

and the files looked like below. All the files are identical except for the name of the .so file was changed.  (Similar to, but not exactly the same as, what is described [here](https://askubuntu.com/questions/442357/environment-setup-for-importing-a-userdefined-module#).)

```
def __bootstrap__():
    global __bootstrap__, __loader__, __file__
    import sys, pkg_resources, importlib.util
    __file__ = pkg_resources.resource_filename(__name__, 'clifford12.cpython-38-darwin.so')
    __loader__ = None; del __bootstrap__, __loader__
    spec = importlib.util.spec_from_file_location(__name__,__file__)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
__bootstrap__()
```

When I build under MacOS 12.3, these bootstrap .py files do not get generated and the libraries cannot be found. Using LD_LIBRARY_PATH didn't help. I copied these Python files from my previous build under MacOS 12.1 into the `venv/lib/python3.8/site-packages/mmgroup-0.0.7-py3.8-macosx-10.14-x86_64.egg/mmgroup`. And then I also copied the newly compiled .so files from `src/mmgroup` into the same place. Then I can successfully `import mmgroup` in Python.

**Comment by Martin-Seysen** [comment]
I have changed function bitmatrix64_rot_bits in file bitmatrix64.ske. In the old
version a 64-bit integer variable has been shifted left by 64 bits in some cases.
The behaviour of this operation is implementation dependent.

I hope that this change fixes the problem.

**Comment by hwatheod** [comment]
I re-built with the latest version, and all of the tests are now passing. Thank you!
